FROM python:3.12-slim-bullseye

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
 --mount=type=bind,source=uv.lock,target=uv.lock \
 --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
 uv sync --frozen --no-install-project --no-editable

COPY /rest /app/rest

COPY main.py /app/main.py

EXPOSE 8501

CMD [ "uv", "run", "-m", "streamlit", "run", "main.py", "--server.port","8501"]
