.PHONY: backend-v1
backend-v1:
	  docker build -f Dockerfile.basic -t backend:0.0.1 .

.PHONY: backend-v2
backend-v2:
	  docker build -f Dockerfile.standard -t backend:0.0.2 .

.PHONY: backend-v3
backend-v3:
	  docker build -f Dockerfile.standardv2 -t backend:0.0.3 .

.PHONY: backend-v4
backend-v4:
	  docker build -f Dockerfile.advanced -t backend:0.0.4 .

.PHONY: backend-v5
backend-v5:
	  docker build -f Dockerfile.advancedv2 -t backend:0.0.5 .

.PHONY: backend-v6
backend-v6:
	  docker build -f Dockerfile.chiselled -t backend:0.0.6 .

.PHONY: backend-v7
backend-v7:
	  docker build -f Dockerfile.chiselled.full -t backend:0.0.7 .
