name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pull-requests: read
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image

        run: |
            cd junia-automatic-deployment-frontend
            docker build -f Dockerfile.basic -t ghcr.io/toino8/junia-automatic-deployment-frontend:${{ github.sha }} .

      - name: Install and run Container Structure Tests
        run: |
          cd junia-automatic-deployment-frontend
          curl -LO https://github.com/GoogleContainerTools/container-structure-test/releases/latest/download/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          mkdir -p $HOME/bin
          export PATH=$PATH:$HOME/bin
          mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
          container-structure-test test --image ghcr.io/toino8/junia-automatic-deployment:${{ github.sha }} --config tests/cst-basic.yaml




      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push the Docker image
        run: docker push ghcr.io/toino8/junia-automatic-deployment:${{ github.sha }}
