name: Build and Push Docker Images

on:
  push:
    branches:
      - "main"
    
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Frontend Docker image
        run: |
          cd junia-automatic-deployment-frontend
          docker build -f Dockerfile.basic -t ghcr.io/toino8/junia-automatic-deployment-dockerisation:${{ github.sha }} .

      - name: Install and run Container Structure Tests for Frontend
        run: |
          cd junia-automatic-deployment-frontend
          curl -LO https://github.com/GoogleContainerTools/container-structure-test/releases/latest/download/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          mkdir -p $HOME/bin
          export PATH=$PATH:$HOME/bin
          mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
          container-structure-test test --image ghcr.io/toino8/junia-automatic-deployment-dockerisation:${{ github.sha }} --config tests/cst-basic.yaml

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push the Frontend Docker image
        run: docker push ghcr.io/toino8/junia-automatic-deployment-dockerisation:${{ github.sha }}

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Push Backend Docker images
        run: |
          cd junia-automatic-deployment-backend
          docker build -f Dockerfile.basic -t ghcr.io/toino8/junia-automatic-deployment-dockerisation:${{ github.sha }} .
        

      - name: Install and run Container Structure Tests for Backend
        run: |
          cd junia-automatic-deployment-backend
          curl -LO https://github.com/GoogleContainerTools/container-structure-test/releases/latest/download/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          mkdir -p $HOME/bin
          export PATH=$PATH:$HOME/bin
          mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
          container-structure-test test --image ghcr.io/toino8/junia-automatic-deployment-dockerisation:${{ github.sha }} --config tests/cst-basic.yaml
         
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Push the Backend Docker images
        run: |
          docker push ghcr.io/toino8/junia-automatic-deployment-dockerisation:${{ github.sha }}
        
